import { ChangeEvent, FormEvent } from "react";
import type { AutomationIntent, Chat, DocumentOption, EntrepreneurPackage, Message, QuickReply, SavedSticker } from "../lib/types";
import { ConversationPanel } from "./ConversationPanel";

type Props = { chat: Chat | null; messages: Message[]; draft: string; uploadingAudio: boolean; uploadingMedia: boolean; documentOptions: DocumentOption[]; selectedDocumentId: string; documentCaption: string; entrepreneurPackages: EntrepreneurPackage[]; quickReplies: QuickReply[]; stickers: SavedSticker[]; replyToMessage: Message | null; onDraftChange: (value: string) => void; onSendText: (event: FormEvent) => void; onReplyToChange: (message: Message | null) => void; onUploadAudio: (event: ChangeEvent<HTMLInputElement>) => void; onUploadImage: (event: ChangeEvent<HTMLInputElement>) => void; onUploadVideo: (event: ChangeEvent<HTMLInputElement>) => void; onUploadDocument: (event: ChangeEvent<HTMLInputElement>) => void; onDocumentChange: (mediaId: string) => void; onDocumentCaptionChange: (caption: string) => void; onSendDocument: () => void; onSendEntrepreneurPackages: (packageIds: string[]) => Promise<void>; onSendSticker: (stickerId: string) => Promise<void>; onRecordAudio: (audio: Blob, filename: string) => Promise<void>; onAutoReplyChange: (enabled: boolean) => void; onScenarioChange: (enabled: boolean) => void; automationIntents: AutomationIntent[]; onLearnIntent: (messageId: string, intentId: string) => Promise<void>; onDeleteConversation: () => void; onClose: () => void };

export function ConversationModal({ chat, messages, draft, uploadingAudio, uploadingMedia, documentOptions, selectedDocumentId, documentCaption, entrepreneurPackages, quickReplies, stickers, replyToMessage, onDraftChange, onSendText, onReplyToChange, onUploadAudio, onUploadImage, onUploadVideo, onUploadDocument, onDocumentChange, onDocumentCaptionChange, onSendDocument, onSendEntrepreneurPackages, onSendSticker, onRecordAudio, onAutoReplyChange, onScenarioChange, automationIntents, onLearnIntent, onDeleteConversation, onClose }: Props) {
  if (!chat) return null;
  return <div className="conversation-modal" role="dialog" aria-modal="true" aria-label={`Conversación con ${chat.name || chat.phone_number}`}><div className="modal-backdrop" onClick={onClose} /><div className="modal-content"><ConversationPanel chat={chat} messages={messages} draft={draft} uploadingAudio={uploadingAudio} uploadingMedia={uploadingMedia} documentOptions={documentOptions} selectedDocumentId={selectedDocumentId} documentCaption={documentCaption} entrepreneurPackages={entrepreneurPackages} quickReplies={quickReplies} stickers={stickers} replyToMessage={replyToMessage} onDraftChange={onDraftChange} onSendText={onSendText} onReplyToChange={onReplyToChange} onUploadAudio={onUploadAudio} onUploadImage={onUploadImage} onUploadVideo={onUploadVideo} onUploadDocument={onUploadDocument} onDocumentChange={onDocumentChange} onDocumentCaptionChange={onDocumentCaptionChange} onSendDocument={onSendDocument} onSendEntrepreneurPackages={onSendEntrepreneurPackages} onSendSticker={onSendSticker} onRecordAudio={onRecordAudio} onAutoReplyChange={onAutoReplyChange} onScenarioChange={onScenarioChange} automationIntents={automationIntents} onLearnIntent={onLearnIntent} onDeleteConversation={onDeleteConversation} onClose={onClose} /></div></div>;
}
