import { DragEvent, FormEvent } from "react";
import { initials } from "../lib/format";
import type { Chat, LeadColumn } from "../lib/types";

type Props = { columns: LeadColumn[]; canEdit: boolean; columnName: string; draggingLeadId: string | null; onColumnNameChange: (value: string) => void; onAddColumn: (event: FormEvent) => void; onRemoveColumn: (column: LeadColumn) => void; onOpenLead: (lead: Chat) => void; onDragStart: (event: DragEvent<HTMLButtonElement>, leadId: string) => void; onDragEnd: () => void; onDrop: (event: DragEvent<HTMLElement>, columnId: string) => void };

export function LeadBoard({ columns, canEdit, columnName, draggingLeadId, onColumnNameChange, onAddColumn, onRemoveColumn, onOpenLead, onDragStart, onDragEnd, onDrop }: Props) {
  return <section className="pipeline" aria-label="Tablero de leads"><header className="pipeline-header"><div><p>PIPELINE COMERCIAL</p><h1>Leads</h1><span>Arrastra una tarjeta para actualizar su proceso comercial.</span></div>{canEdit && <form onSubmit={onAddColumn} className="add-column"><input value={columnName} onChange={(event) => onColumnNameChange(event.target.value)} maxLength={80} placeholder="Nueva columna" /><button>Agregar columna</button></form>}</header><div className="kanban" role="list">{columns.map((column) => <section className="lead-column" key={column.id} onDragOver={(event) => event.preventDefault()} onDrop={(event) => onDrop(event, column.id)}><header><div><h2>{column.name}</h2><span>{column.leads.length} {column.leads.length === 1 ? "lead" : "leads"}</span></div>{canEdit && <button className="remove-column" onClick={() => onRemoveColumn(column)} aria-label={`Eliminar ${column.name}`}>×</button>}</header><div className="lead-stack">{column.leads.map((lead) => <button className={draggingLeadId === lead.id ? "lead-card dragging" : "lead-card"} key={lead.id} draggable onDragStart={(event) => onDragStart(event, lead.id)} onDragEnd={onDragEnd} onClick={() => onOpenLead(lead)}><span className="lead-avatar" aria-hidden="true">{initials(lead.name || lead.phone_number)}</span><span><strong>{lead.name || lead.phone_number}</strong><small>{lead.phone_number}</small><em>{lead.last_message || "Sin mensajes aún"}</em></span></button>)}{column.leads.length === 0 && <p className="empty-column">Arrastra leads aquí</p>}</div></section>)}</div></section>;
}
